version: '3'

services:
  nuxt-app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    command: >
      sh -c "npm install -g pnpm &&
             pnpm install &&
             pnpm run dev"

volumes:
  pnpm-store: